### ISSUE TITLE
🐞 [Android] Expedited tasks don't work

### ISSUE THREAD

**Issue by iazel** [fluttercommunity/flutter_workmanager#452] opened 2023-01-15 17:07 UTC
- [x] I have read the [README](https://github.com/vrtdev/flutter_workmanager/blob/master/README.md)
- [x] I have done the setup for [Android](https://github.com/vrtdev/flutter_workmanager/blob/master/ANDROID_SETUP.md)
- [x] I have done the setup for [iOS](https://github.com/vrtdev/flutter_workmanager/blob/master/IOS_SETUP.md)
- [ ] I have ran the sample app and it does not work there

**Version**

| Technology           | Version       |
| -------------------  | ------------- |
| flutter_workmanager  |      0.5.1         |
| Android API | 33 |

**Describe the error**
It is currently not possible to use expedited tasks (i.e. by providing a value for `outOfQuotaPolicy`) due to a change in WorkManager version 2.7 that now requires all `ListenableWorker` to implement the `getForegroundInfoAsync` method.

The current failure message is as follows:
```
Expedited WorkRequests require a ListenableWorker to provide an implementation for `getForegroundInfoAsync()`
```

I may give you some support with this if needed, but not sure how to handle the Notification part. I think the easiest first step would be to have a simple message and let the library users pass it, something like:
```dart
WorkManager().registerOneOffTask(
  "unique-id", "uploading",
   expedited: Expedited(notification: "Uploading items in background", policy: OutOfQuotaPolicy.drop_work_request),
)
```

This will break the API though and require a major version upgrade. What do you think? 

**Output of `flutter doctor -v`**
```
[✓] Flutter (Channel stable, 3.3.10, on Ubuntu 22.04.1 LTS 5.15.0-58-generic, locale en_US.UTF-8)
    • Flutter version 3.3.10 on channel stable at /home/iazel/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (4 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /home/iazel/Android/Sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /snap/android-studio/125/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Android Studio (version 2021.3)
    • Android Studio at /snap/android-studio/125/android-studio
    • Flutter plugin version 71.2.3
    • Dart plugin version 213.7433
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] Connected device (1 available)
    • ONEPLUS A5000 (mobile) •  android-arm64  • Android 10 (API 29)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by dayron9110** [comment] 2023-05-28 15:46
Any news regarding this feature?

**Comment by ened** [comment] 2023-06-03 23:22
duplicate of #236 - please follow along there

**Closed by ened** 2023-06-03 23:22 UTC
Labels: bug

**Comment by orkun1675** [comment] 2025-01-28 03:33
FYI I don't think this is a duplicate of https://github.com/fluttercommunity/flutter_workmanager/issues/236.

IIUC Android 30 and below workers need to implement the `getForegroundInfoAsync` method. We encoutered the same issue for the [native_geofence plugin](https://pub.dev/packages/native_geofence).

The fix can be seen in this commit: https://github.com/ChunkyTofuStudios/native_geofence/commit/2f32a254aab602c0319b4af984b62d3aa9d20577
