### ISSUE TITLE
Interact with app when running in foreground?

### ISSUE THREAD

**Issue by iazel** [fluttercommunity/flutter_workmanager#449] opened 2022-12-09 17:17 UTC
Hello,

as per title, is there any way to exchange data between the worker isolate and the app main thread when the latter is running in the foreground?

**Comment by bakua** [comment] 2022-12-24 07:11
Hi, you could have a look at cross isolate communication https://dart.dev/guides/language/concurrency#sending-multiple-messages-between-isolates

**Comment by iazel** [comment] 2022-12-24 09:29
> Hi, you could have a look at cross isolate communication https://dart.dev/guides/language/concurrency#sending-multiple-messages-between-isolates

Hi, thanks for the recommendation but I've already looked into it.

The issue here is that we spawn the isolate on the native side and the flutter app is completely ignorant of it. As far as I can see, there is no way to send a Port to it, hence the problem.

**Comment by iazel** [comment] 2023-02-24 16:43
> There is actually a way, [using `IsolateNameServer` from `dart:ui`](https://api.flutter.dev/flutter/dart-ui/IsolateNameServer-class.html). From the main isolate you should use `IsolateNameServer.registerPortWithName(SendPort port, String name)` to register the port, then from the work isolate you should use `IsolateNameServer.lookupPortByName(String name)` to get that port and send messages through it. I am using this on Android and it is working.

Oh, didn't know that, thanks for sharing! I wonder why this is in `dart:ui` instead of `dart:isolate`, quite puzzling.

**Comment by luis901101** [comment] 2023-03-16 22:58
Duplicate of https://github.com/fluttercommunity/flutter_workmanager/issues/151

**Closed** 2023-04-02 14:28 UTC
